### PR TITLE
bump github.com/elazarl/goproxy

### PR DESCRIPTION
**Pull request by gpaul**
This PR updates `github.com/elazarl/goproxy` for https://github.com/elazarl/goproxy/pull/218 so octarine works with Go 1.8.

Updates https://jira.mesosphere.com/browse/DCOS_OSS-1322

### CODE REVIEW

**Comment by gpaul** [comment]
@nlsun PTAL

**Review by nlsun — APPROVED** [review]
@gpaul  looks good, merge at will

**Comment by nlsun** [comment]
Also, would you like to open the dc/os PR as well?

**Comment by gpaul** [comment]
@nlsun Just noticed I don't have commit rights to this repo, would you mind merging?

**Comment by gpaul** [comment]
I'll follow up with a dcos bump PR

**Comment by nlsun** [comment]
@gpaul thanks!

**Pull request merged**
